/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Atmospace: typeof import('./components/Atmospace.vue')['default']
    Auramine: typeof import('./components/Auramine.vue')['default']
    BackgroundParallax: typeof import('./components/BackgroundParallax.vue')['default']
    DataView: typeof import('./components/DataView.vue')['default']
    Discord: typeof import('./components/Discord.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Vortex: typeof import('./components/Vortex.vue')['default']
  }
}
